### ISSUE TITLE
Plugin can't be enabled on mobile obsidian

### ISSUE THREAD

**Issue by shabegom** [jensmtg/influx#1]
I'm interested in trying out this plugin! I can't enable it on my iPad. Is this intentional?

**Comment by cfritze64** [comment]
same question here

**Comment by FelipeRearden** [comment]
Would be amazing to have this plugin on Mobile 🙏🙏🙏

**Comment by jensmtg** [comment]
It's not a bug, but intentional in the sense that I've set `isDesktopOnly` to true in the manifest, but this is mainly because I haven't tested it towards a mobile environment.
The interest is noted though, will see if there is a quick fix to this.
