### ISSUE TITLE
Influx uses the first header in a file not the one closest/enclosing a reference.

### ISSUE THREAD

**Issue by stoweboyd** [jensmtg/influx#11]
I have a reference to `[[influx notes]]` at the bottom of a daily note. 

![Screen Shot 2022-09-17 at 3 34 07 PM](https://user-images.githubusercontent.com/3037422/190873745-98a05ddb-38c8-4e4d-b543-cf324a20d940.png)

But the influx data at the foot of that file shows a header from the top of the file, `do today`, not the expected `3:06 PM trying to influx`.

![Screen Shot 2022-09-17 at 3 36 56 PM](https://user-images.githubusercontent.com/3037422/190873782-84ea8059-908e-4043-988f-ab52707dff25.png)

**Comment by jensmtg** [comment]
Influx uses the first header in a note as a header for that note. Other then that, it only processes hierarchical data (bullet lists). As such, this is expected behaviour per se, but I may add an option to disable note headers in Influx.

**Comment by jensmtg** [comment]
Partially fixed in latest version.
