### ISSUE TITLE
Callouts do not work well in influx if they contain a mention

### ISSUE THREAD

**Issue by DeutscheGabanna** [jensmtg/influx#15]
the padding is too large. The influx record doesn't have to be a callout (maybe it even shouldn't be), but could you please decrease the padding to make it look like normal text?

**Comment by jensmtg** [comment]
Can you share an image of what you mean?

**Comment by DeutscheGabanna** [comment]
![image](https://user-images.githubusercontent.com/59067099/191285206-0a524c0e-4e0c-4b15-88fa-981fa2b0d65a.png)
![image](https://user-images.githubusercontent.com/59067099/191285159-510abe49-ec39-4d77-b264-ddcd22281a5a.png)

**Comment by DeutscheGabanna** [comment]
also this:
![image](https://user-images.githubusercontent.com/59067099/191285433-bf74f7d5-bd0f-4290-a844-6249586d4355.png)

**Comment by jensmtg** [comment]
Thanks! That's buggy for sure.
