### ISSUE TITLE
Influx reopens a few seconds/keystorkes after being minimized.

### ISSUE THREAD

**Issue by cansar** [jensmtg/influx#18]
I really love the new minimize ability but if I type a few lines above it it seems to quickly open back up again. Let me know if you can reproduce this or need a Loom, etc.

**Comment by cansar** [comment]
Text will also sometimes appear _below_ the Influx links for a brief moment while typing, so I think that's related.

**Comment by jensmtg** [comment]
I *think* this bug is fixed now. At least I'm no longer able to reproduce this bug myself anymore. Please make a new issue if you can find a way this bug still appears.
