### ISSUE TITLE
[Bug?] Wrapping for smaller panes doesn't work with minimal

### ISSUE THREAD

**Issue by danieltomasz** [jensmtg/influx#2]
Great plugin! It offers something really similar that Logseq for bullet journal and what obsidian lacked

What I observed that the output isn't wrapped on Minimal theme (which is so far most popular user theme)
<img width="598" alt="image" src="https://user-images.githubusercontent.com/7980381/189501408-f8d654e7-dae9-4e37-97bc-0328ac029642.png">

It works on vanilla 
<img width="677" alt="image" src="https://user-images.githubusercontent.com/7980381/189501562-1efcd76b-39e4-493e-9056-6b81653aa718.png">

I am on obsidian 0.16.2
This should be posted on Minimal theme discord/github, but maybe there is an easy fix within plugin
I notice that @jensmtg  you are still on 0.15.9, maybe the problem isn't there?

**Comment by jensmtg** [comment]
If there's an easy fix to this I will implement it in the next update, but issues that are not on the latest/stable version (0.15) is generally not a priority.

**Comment by danieltomasz** [comment]
Work fine with Vanilla theme, for me  might wait :) Thank you  again for making this plugin :)

**Comment by jensmtg** [comment]
Should be fixed in the latest version.
