### ISSUE TITLE
Influx does not support new windows very well

### ISSUE THREAD

**Issue by DeutscheGabanna** [jensmtg/influx#21]
This is how influx records are shown when displaying a note in a new window instead of the main one.
![image](https://user-images.githubusercontent.com/59067099/192219832-43cb26a2-12c0-436e-93ac-1d925ced7a8e.png)

**Comment by jensmtg** [comment]
Seems to be an issue with Obsidian that it doesn't handle jss in popout windows. Awaiting clarifications; https://discord.com/channels/686053708261228577/716028884885307432/1026115305098973354
