### ISSUE TITLE
Can't see sparse list of mentions if filename starts with a uppercase letter links start with a lowercase letter

### ISSUE THREAD

**Issue by minkkinen** [jensmtg/influx#23]
I have many links that refer to files in the middle of the sentence and the link starts with a lowercase letter. The filename of the linked file starts in uppercase. This works fine in Obsidian, and I can see the files as linked in influx. However, I can't see the sparse list of mentions for those ones where this uppercase/lowercase issue exists. Is this easily fixable in influx or is it something more complicated?

**Comment by jensmtg** [comment]
Sounds like an easy fix. Can you provide a concrete example?

**Comment by minkkinen** [comment]
I can’t get to my work computer now to get screenshots but I’ll try to give an example.

I have a note called “Business models” (starts with a capital B). In another note (called berente2021managing), I have the passage “… inventing new [[business models]]” (with a lowercase b). When I open the Business models note, influx rightly shows the berente2021managing note, but influx doesn’t show the passage under it (the one with the link). I’m guessing this is because of the uppercase-lowercase issue, so influx apparently doesn’t consider it a mention.

Hope that helps.
