### ISSUE TITLE
Slight padding issues with normal text

### ISSUE THREAD

**Issue by pawel-ilnicki** [jensmtg/influx#27]
![image](https://user-images.githubusercontent.com/98173950/196675218-42a755fa-d252-4ebc-9456-d66ddb716f19.png)

This is the actual markdown - as you can see it's absolutely basic:
```
---
tags: type/meeting
held: 2022-09-08
---
[[ocena pracownika|ocena]] roczna: **fusion** i inne chuje muje
```

So why does the influx mention have such strange asymmetrical padding?

**Potential solutions**:
First:
![image](https://user-images.githubusercontent.com/98173950/196675830-470aab06-16e8-4f9b-af3a-7fe04eda42dc.png)

Second:
![image](https://user-images.githubusercontent.com/98173950/196675973-127bf8ec-2858-473d-9d12-9bbbd8c654d9.png)

**Comment by jensmtg** [comment]
Fixed.
