### ISSUE TITLE
Plugin not loading 

### ISSUE THREAD

**Issue by pcuellar** [jensmtg/influx#28]
Thanks for the plugin, I am using it heavily. Just saw the 2.0.3 update and noticed the plugin is not loading anymore. If I disable it and enable it again, I get this warning. I am on Obsidian v1.0.0, same version number installer 

<img width="427" alt="Screen Shot 2022-10-19 at 9 31 29 AM" src="https://user-images.githubusercontent.com/20482146/196706071-c542b7a2-3f0a-4e05-9c0f-e86cbedbe862.png">

**Comment by jensmtg** [comment]
Thanks!

That shouldn't cause a problem. Have you tried reloading obsidian?

**Comment by pcuellar** [comment]
I did but the plugin does not appear to load when I look at the console. I just uninstalled and install it back up and it is still not showing up.

**Comment by jensmtg** [comment]
I'm unable to reproduce this bug. The difference between 2.0.2 and 2.0.3 is furthermore so small that it's hard to imagine it could cause the plugin to stop working.
What is your last working version of the plugin?
You are familiar with the fact that as of version 2 influx does not show up unless there are inbound mentions in a page?

**Comment by danieltomasz** [comment]
For me plugin  is working
@pcuellar did you try to to install it via plugin library in the sandbox vault?
Could you share reproducible example?

@jensmtg maybe could could create a templates for bugs and feature request with checklist for all steps to do, now you will probably more people coming to this repo as it is now officially in the plugin library

**Comment by pcuellar** [comment]
I see what's going on. The displaying of the results is different. There used to be an 'influx' blue title under which results were displayed. This has now changed to a panel that looks very much like the Obsidian core 'Linked mentions panel'.
