### ISSUE TITLE
Higher level bullet point do not render as bullet point

### ISSUE THREAD

**Issue by danieltomasz** [jensmtg/influx#30]
I have a text

```
- #test 
	- [[test]]
```
which is rendered as 
<img width="636" alt="image" src="https://user-images.githubusercontent.com/7980381/196766613-cc41da7e-0586-4087-a7bf-f32d77cf68ef.png">

I would expect it to render same way as in live preview
<img width="203" alt="image" src="https://user-images.githubusercontent.com/7980381/196767196-72772445-64a2-45a9-8185-0df4a742dc92.png">

Obsidian 1.0
Plugin version 2.0.3

**Comment by jensmtg** [comment]
Fixed.

**Comment by danieltomasz** [comment]
Thanks for fixing it! 
Now the vanilla theme works great, but I see  a problem with Minimal
The tag is below the line of bullet
<img width="685" alt="image" src="https://user-images.githubusercontent.com/7980381/197156581-72b5ad48-72ca-45a7-89f6-587e6fba60f3.png">

I dont know if this is related to this update of Influx, or the current updates in minimal (probably the second), I will comment later on minimal discord thread/fill GitHub issue
