### ISSUE TITLE
Influx unnecessarily shows mentions within the note itself

### ISSUE THREAD

**Issue by DeutscheGabanna** [jensmtg/influx#31]
If a note XYZ.md [[mentions]] itself or its [[^^block]], influx shows such mentions just like mentions from external notes.
![image](https://user-images.githubusercontent.com/59067099/196770128-98053796-4c77-43c9-a3c0-5f7764f17a78.png)

Maybe this behaviour could be disabled or made a toggleable option?

I'm looking at the file "journey of sorrow.md" and see this:
![image](https://user-images.githubusercontent.com/59067099/196770185-ed47a633-720b-457b-a184-df846cbfe0d0.png)

**Comment by jensmtg** [comment]
Fixed
