### ISSUE TITLE
Add settings toggle for default opt-in or opt-out of influx segment; add settings inputs for inclusion and exclusion patterns

### ISSUE THREAD

**Issue by danieltomasz** [jensmtg/influx#4]
Allow for excluding folders and notes, for example I would like to my folder with templates be excluded from influx footnotes.

**Comment by pawel-ilnicki** [comment]
Yes, since the main premise of influx is referencing daily note mentions, why on earth does the plugin display **all** mentions in the influx footnote?

**Comment by jensmtg** [comment]
Because on earth time constraints are a thing. 😂
But don't worry, this feature is essentially done, currently in testing.

**Comment by DeutscheGabanna** [comment]
Ah, I haven't considered it. Sorry.

**Comment by jensmtg** [comment]
Fixed in latest version.
