### ISSUE TITLE
[bug] Newly typed text  in long paragraphs sometimes is displayed below influx section for a few seconds for large notes (Uncaught range error?)

### ISSUE THREAD

**Issue by danieltomasz** [jensmtg/influx#40]
It happens with live text and and live text turned off in the Influx, Obsidian is in Live Preview mode.

When I have a note with large number of linked mentions (lets say 20, the are not visible without scrolling) I sometimes observe the following behaviour:
-  when I have the large paragraph to type (in bullet points), the text I type sometimes  appear below the Influx section for a few seconds and then the cursor came back to the "proper" section of the note
- the text is in its proper place, dont disseappers, but it is just displayed for a few seconds as it were below the Influx section
- I didnt observed this in a notes with small amount of linked mentions
- even if I collapse the references, after a few typed words, the linked mentions un-collapse and the type words appears again on the bottom of the pane, below the Influx linked mentions, and then the  typed text slowly (sometimes letter by letter) appear again in the line when I typed it
- when this is happening I saw this in the developer console, not sure if related
```
Uncaught RangeError: Position 396 is out of range for changeset of length 395
    at t.e.mapPos (app.js:1:270074)
    at e.map (app.js:1:302081)
    at e.update [as updateF] (plugin:influx:23527:15)
    at Object.update (app.js:1:283426)
    at e.computeSlot (app.js:1:294218)
    at Fn (app.js:1:287369)
    at new e (app.js:1:293244)
    at e.applyTransaction (app.js:1:294160)
    at e.get (app.js:1:289373)
    at e.update (app.js:1:434795)
```

I will try to make a gif to make it better to see what is happening.
I also try to turn off other plugins, to see if this persist
MacOS 13, Obisidian, 1.02, Influx 2.0.7

**Comment by danieltomasz** [comment]
I recorded the screen, with recoding the behaviour is even worse (so maybe this is about computational resources - BTW I am on M1 macbook pro, so this shouldnt be a problem)
https://www.loom.com/share/6c5189fbc5424592b1a829e7d48f042a

**Comment by danieltomasz** [comment]
The one thing that come to my mind that this beta plugin I started using could mess up with the Influx function calls and internal states https://github.com/TfTHacker/obsidian42-strange-new-worlds
(But probably not)

**Comment by jensmtg** [comment]
Thanks for an extensive bug report! This is #8 and #29 I suspect, but will check it out when I get a chance.

**Comment by danieltomasz** [comment]
Reading the issues I think I found the cause, it might be Minimal with wide dataview  view enabled
- when I switched to vanilla Obsidian the jumping stopped, the dataview still disappears stops working for a few seconds, when I type really fast but there coursor and the text doesn't move, altought the  influx view is still "jumpy" and flashy, as it turning on and off for miliseconds (the live update is off)
https://www.loom.com/share/b792bf10c6cc42c4b85355ab02dccab9
- so i think there are 2 bugs
-  influx stopping displaying and redrawing everything when I typed fast
- when influx redraw it interfers with dataview and others plugins that expand dataview like this one https://github.com/efemkay/obsidian-modular-css-layout
- when there any many linked notes it just take much longer to redraw and this is more visible to the eye when in case of only a few

(BTW I just found  in the video another bug related to text in bullet points but this is not influx related :P )  
https://www.loom.com/share/b792bf10c6cc42c4b85355ab02dccab9

**Comment by danieltomasz** [comment]
Maybe a way to investigate the issue (MVE);
- Typing really fast un-collapse all linked mentions, forcing collapsing to be persistent might be a workaround (until uncollapsing) , the collapsed view is still jumping but the jumping is much less invasive

**Comment by mediapathic** [comment]
Just to add a couple of data points here:

I am also seeing this behavior, but it does not require a large number of linked notes for me; I see it on notes that have only one or two. I'm using the default theme. I don't get the "text appears under links" consistently, but even when that doesn't happen I still have the list of links disappearing and reappearing while I type (and, with typewriter scroll turned on, this causes the entire document to leap up and down, which is extra annoying).

**Comment by danieltomasz** [comment]
The other way to make this visible is to enable the vanilla backlinks to actually see diseappearing and appering of the plugin (obsidian baclinks go up and down in the moment the influx is not rendered); as I think, the error happens in small number of notes, but it might be harder to catch by eye as the only a few of backlinks are rendered much faster (it will also  depends from how fast the computer is too)

**Comment by jensmtg** [comment]
It's a bug related to how codemirror handles widget extensions.
As such, I can't fix this directly, but I have an idea for a work-around that I think will essentially solve the problem. I'll probably get a chance to explore it sometime in the coming month.

**Comment by emory** [comment]
i wish i would have checked in here first because i'm seeing the same behavior and it sometimes stomps on in-line edits while i'm writing a note! i thought it was related to tag autocomplete or something but it drives me bonkers because it even re-arranges words while i'm writing sometimes. 

a brief demonstration from my workstation (12-core i7 MBP touchbar with 32GB of memory) https://www.dropbox.com/s/059vzx7fpa2pr2o/CleanShot%202022-11-03%20at%2016.44.16.mp4?dl=0 

this happens in every note i type in; daily or meeting notes, content maps — the vault from the example above has 2700 markdown documents and 9200 files total, most of my vaults are also git repositories though and the `.git` directory on this particular vault has 3000 files in it. i have configured Influx to operate (include) in my daily notes tree, my zettelkasten tree, my PARA Projects/Areas/Resources/Archive directories. 

```
RedactedVault % find . -type f -name "*md" | wc -l
    2752
RedactedVault% find . -type f | wc -l
    9286
```
this workstation doesn't run very smoothly but i have IO and cpu time to spare. only thing that may be unusual is that i routinely have a lot of open files. my obsidian vaults are also indexed by DEVONthink. Open and Save dialog boxes can hang for up to minute for some reason that i've never been able to remediate.

**Comment by cathywu** [comment]
I'm also experiencing this issue, as well as what's mentioned by @zcysxy.

**Comment by dummylabs** [comment]
Have the same issue on my macbook pro.

**Comment by pawel-ilnicki** [comment]
I encourage people irritated by this bug to include an additional line at the end of all your most-used templates:

```
<% tp.file.cursor(1) %>

%% This line stops influx from misbehaving %%
```

What this achieves is prevents the bug from occurring by having another line below where you type. `file.cursor()` moves your cursor up after pasting the template, so you don't have to do it manually.

**Comment by jensmtg** [comment]
@pawel-ilnicki Interesting work-around! No, I've not had the chance to develop this plugin further for a long time, unfortunately. (Life eats you up!) Hopefully I'll get a chance to do so before summer.

**Comment by farid56x** [comment]
> I encourage people irritated by this bug to include an additional line at the end of all your most-used templates:
> 
> ```
> <% tp.file.cursor(1) %>
> 
> %% This line stops influx from misbehaving %%
> ```
> 
> What this achieves is prevents the bug from occurring by having another line below where you type. `file.cursor()` moves your cursor up after pasting the template, so you don't have to do it manually.

it works, big thanks! I still have some performance issues with big files, but I can handle that for now.

**Comment by alranel** [comment]
I'm experiening this as well and sadly it's a showstopper which is a pity because I love this plugin :) 
@jensmtg, any chance you can elaborate on the workaround you have in mind as mentioned above? That way someone might try to implement it.

**Comment by jensmtg** [comment]
The workaround that hides influx while typing is in place with the latest version, as an optional but default setting, so this issue should be solved now - to the extent that it can be without access to obsidian internals.

**Comment by zcysxy** [comment]
The workaround works great! However, when influx disappears, the editor view also moves.

https://user-images.githubusercontent.com/48207708/219582180-4ab097f6-a136-408e-9e58-7b58f85d3f20.mov
