### ISSUE TITLE
Wrong hierarchy for child nodes

### ISSUE THREAD

**Issue by zhechenghu** [jensmtg/influx#41]
Hi, this is useful for organizing my meeting notes, which are always just collections of points and views! Thanks a lot! But during usage, I found that the child nodes are all in the same hierarchy as the node where the wiki link is, as shown below.

Original file

<img width="421" alt="image" src="https://user-images.githubusercontent.com/100691508/197385371-3d7cc6a0-4241-499b-92b1-1a8604649eee.png">

Backlinks

<img width="769" alt="image" src="https://user-images.githubusercontent.com/100691508/197385383-d42db0ed-f3e5-4f8a-a701-e0552c3e49a3.png">

Thanks again for developing this plugin!

**Comment by Hu-Zhecheng** [comment]
It seems the hierarchy for the bullet lists is correct.

**Comment by jensmtg** [comment]
Implemented/fixed in latest version.
