### ISSUE TITLE
Wrong sorting

### ISSUE THREAD

**Issue by scriptor-dga** [jensmtg/influx#44]
The sorting of the dates is wrong.

![image](https://user-images.githubusercontent.com/59956700/198566138-f6e71df5-d823-448b-bcd6-217230ceade9.png)

**Comment by jensmtg** [comment]
This could be because of your settings, but it's impossible to help you without more context of the problem. Please follow the bug report template when registering issues.

**Comment by scriptor-dga** [comment]
> This could be because of your settings, but it's impossible to help you without more context of the problem. Please follow the bug report template when registering issues.

here are the relevant setting
![image](https://user-images.githubusercontent.com/59956700/198584193-5eab2306-cc6e-413a-9721-4cf35a67b275.png)
