### ISSUE TITLE
Checkbox misaligned

### ISSUE THREAD

**Issue by yimingli** [jensmtg/influx#45]
**Describe the bug**
Checkboxes are misaligned in the influx view.

![SCR-20221030-wl1](https://user-images.githubusercontent.com/4153781/198945537-09e73ead-0041-4ff9-874d-25926fd5d945.png)

![SCR-20221030-wob](https://user-images.githubusercontent.com/4153781/198945655-48609044-9400-4dce-83b2-f96e065e297f.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 12.6

**Comment by jensmtg** [comment]
Implemented/fixed in latest version. I think.
