### ISSUE TITLE
Readability of larger texts

### ISSUE THREAD

**Issue by kangruixiang** [jensmtg/influx#46]
When using larger body text in Obsidian, the readability of the backlink goes down because the note titles are on the left side. Example. 

Here's the default backlink from Obsidian. Note titles are above the embeds:
![image](https://user-images.githubusercontent.com/17035138/200122114-2d34a8f1-8943-4d7d-81da-6ad56b68191a.png)

Here's influx. Note titles are to the left. Longer note titles make things worse:
![image](https://user-images.githubusercontent.com/17035138/200122083-246795d5-437d-4be2-9f1b-90ec710da46a.png)

**Comment by jensmtg** [comment]
Implemented/fixed in latest version. I think.
