### ISSUE TITLE
Influx previews are incorrect when backlinks use Markdown Links (with possible solution)

### ISSUE THREAD

**Issue by kenlim** [jensmtg/influx#50]
**Describe the bug**
When a document uses Markdown Links instead of the default "Shortest path when Possible" WikiLinks, Influx does not render the preview correctly. 

**To Reproduce**
1. Create a target note called "target"
2. Create a referring note called "markdown referral"
3. In the note "markdown referral", add the following block of text:

```
# This is the top heading
This is the first paragraph

# This uses Markdown Links
[Target](./target.md) This will not appear in the Influx preview

```
4. Return to "target.md", and observe the Influx widget.
5. Notice that it links to the correct "markdown link" note, but only displays "This is the top heading" 

**Expected behavior**
The Influx widget should link to the correct "markdown link" note, and displays:

```
# This uses Markdown Links
[Target](./target.md) This will not appear in the Influx preview
```

**Screenshots**
![image](https://user-images.githubusercontent.com/111891/208540537-96c5948d-7ff7-415c-84a2-4f225b3d9d0b.png)

**Desktop (please complete the following information):**
 - OS:MacOS
 - Version: 11.6.8
 - influx version: 2.0.7
 - Obsidian version: 1.0.3
 - 
**Additional context**
Influx preview works correctly for "Shortest path when Possible" WikiLinks.

**Comment by kenlim** [comment]
Hey there, I think there is a solution to this. The `compareLinkName` method in the `apiAdapter.tsx` file doesn't return true when the link is a Markdown link. 

with some additional code, you can make it work with Markdown links. 

Very quickly, here it is:

```
compareLinkName(link: LinkCache, basename: string) {
        
    // format link name to be comparable with base names:
    // strip any block references from the end
    const path = link.link;
    const filenameOnly = path.split("/").slice(-1)[0]
    const linkname = filenameOnly.split("#^")[0].split(".md")[0]

    if (linkname.toLowerCase() === basename.toLowerCase()) {
        return true
    }
    return false
    }
```

markdown links that used to fail and will now work:
- "./target.md"
- "./folder/subfolder/target.md"
- "./target.md#^3e2345"

**Comment by kenlim** [comment]
Have raised pull request (https://github.com/jensmtg/influx/pull/51).

**Comment by jensmtg** [comment]
Implemented. Thanks!
