### ISSUE TITLE
Extra line created in reading view

### ISSUE THREAD

**Issue by sawft99** [jensmtg/influx#52]
**Describe the bug**
A reference with nested bullet points results creates an extra line in reading view

**To Reproduce**
1. Create a bullet point with some text
2. Create another bullet point on a new line and indent once
3. Reference the parent bullet point in some way
4. Switch to reading view and there is another line with only the reference counter

**Expected behavior**
To be in its proper place next to the reference

**Screenshots**

## Source view

![image](https://user-images.githubusercontent.com/81699231/210282140-b478cd80-40f8-4d4a-8331-589b6150de3c.png)

## Reading view

![image](https://user-images.githubusercontent.com/81699231/210282170-7cda6e8a-42d6-4273-a5db-67bebb8fed56.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Attempted fixes**
Shortening the sentence made no difference

**Comment by jensmtg** [comment]
Implemented/fixed in latest version. I think.
