### ISSUE TITLE
Influx not Visible in Reading View (?)

### ISSUE THREAD

**Issue by Mocca101** [jensmtg/influx#7]
The Influx View is visible for me in the Live Preview but not in the Reading View (See screenshots). Is that intentional?

![grafik](https://user-images.githubusercontent.com/49754596/189770621-89f9142c-5fc6-4a13-9d62-774b79559bf2.png)
![grafik](https://user-images.githubusercontent.com/49754596/189770659-f24d230e-91f3-47f5-9ee4-7deedd6bd0e1.png)

**Comment by jensmtg** [comment]
It requires a separate implementation, that's why it's not visible yet. Added to requested features.

**Comment by Mocca101** [comment]
Alright, thank you! The plugin is really looking awesome so far as it is.

**Comment by jensmtg** [comment]
Implemented/fixed in latest version.
