### ISSUE TITLE
Slightly broken since Obsidian 1.6.3

### ISSUE THREAD

**Issue by Neeqstock** [jensmtg/influx#87]
**Describe the bug**
Since Obsidian 1.6.3, all the mentions start with the writing `ir="auto">_`, like something wrong is happening in the rendering. Also, when editing any table in Obsidian, the linked mentions show up in the cell.

**To Reproduce**
Open any note with linked mentions; edit a table in a page with linked mentions

**Expected behavior**
No `ir="auto">_`, no linked mentions showing up in tables

**Screenshots**
![2024-06-13_12-24](https://github.com/jensmtg/influx/assets/15343295/3b10b08a-340c-4d20-8e44-1b3694d30d50)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Obsidian version 1.6.3

**Comment by bvsbuild** [comment]
I'm experiencing the same issue and I'm also really sad because I really love this plugin.

**Comment by ivan-lednev** [comment]
This plugin has been discontinued, see https://github.com/ivan-lednev/better-search-views for an analogous functionality.

**Comment by ivan-lednev** [comment]
Can you describe what specific elements of the design you have in mind when saying 'the clean simplicity of Influx'?

**Comment by bvsbuild** [comment]
I think it's really about information density in the backlinks section of individual notes. When using something like a bulleted list with hierarchy, a few entries can really expand and consume a lot of space. I think a few styling tweaks like font-size and indent depth would resolve a lot of it. The two-column layout from influx (note title on the left, content on the right) allows for a quick scan and quick identification of individual notes. Additionally, the headline and bullet list icons in Better Search Views create some visual noise (just for my use case) that breaks from the original formatting of the text. Finally, when a link is included in a headline or the initial list item (like "Web" on the entry from 3/27, it doesn't render as a link, but instead includes brackets. Hopefully the screenshot helps illustrate (excuse the messy redactions). These minor things could clean up how my eye encounters the info and help compress it for my use case. Thanks for asking! 

<img width="1222" alt="Screenshot 2024-06-28 at 2 05 18 PM" src="https://github.com/jensmtg/influx/assets/26068173/0248406b-964d-4eb6-ab3d-1bcc2e3229f7">

**Comment by eXperitur** [comment]
**quick & dirty fix** - since it looks like this plugin will not be updated any more: 

Change line 23493 in **main.js** under `.obsidian/plugins/influx` from:

 ` const titleInnerHTML = titleAsMd.innerHTML.slice(4, -4); ` 
 
 to:
  
  ` const titleInnerHTML = titleAsMd.innerHTML.slice(4, -4).replace('ir="auto">_', ''); `
